use "/Users/ellaedmonds/Downloads/dhsdata (1).dta"
graph pie country, over(pregtermin)
graph pie country, over(pregtermin) missing
graph pie country, over(pregtermin)
graph pie country if = bangladesh, over(pregtermin)
graph pie country if bangladesh, over(pregtermin)
graph pie country, over(pregtermin)
graph pie country in 1/50, over(pregtermin)
graph pie country in 1/818, over(pregtermin)
graph pie country in 60/818, over(pregtermin)
graph pie country, over(pregtermin)
graph pie country, over(pregtermin) sort(country)
graph pie country, over(pregtermin)
graph pie country, over(pregtermin) by(country, total)
graph pie country, over(pregtermin) by(, title(Pie Charts Showing What Proportion of Women Have Terminated a Pregnancy) note(Random Selection Into Participents)) by(country, total)
graph pie country, over(pregtermin) by(, title(Pie Charts Showing What Proportion of Women Have Terminated a Pregnancy, ring(0) margin(small)) note(Random Selection Into Participents)) by(country, total)
graph pie country, over(pregtermin) by(, title(Pie Charts Showing What Proportion of Women Have Terminated a Pregnancy, ring(0) margin(small)) note(**Participents in the survery are randomly selected females from each country)) by(country, total)
graph pie country, over(pregtermin) by(, title(Pie Charts Showing What Proportion of Women Have Terminated a Pregnancy, size(vsmall) orientation(rhorizontal) ring(0) margin(small)) note(**Participents in the survery are randomly selected females from each country)) by(country, total)
graph pie country, over(pregtermin) by(, title(Pie Charts Showing What Proportion of Women Have Terminated a Pregnancy, size(small) orientation(horizontal) ring(0) margin(small) alignment(middle)) note(**Participents in the survery are randomly selected females from each country)) by(country, total)
graph pie country, over(pregtermin) by(, title(Pie Charts Showing What Proportion of Women Have Terminated a Pregnancy, size(small) orientation(horizontal) ring(0) margin(zero) alignment(middle)) note(**Participents in the survery are randomly selected females from each country)) by(country, total)
graph pie country, over(pregtermin) by(, title(Pie Charts Showing What Proportion of Women Have Terminated a Pregnancy, size(small) margin(zero) alignment(middle)) note(**Participents in the survery are randomly selected females from each country)) by(country, total)
graph pie country, over(pregtermin) by(, title(Pie Charts Showing What Proportion of Women Have Terminated a Pregnancy, size(small) margin(zero) alignment(middle)) note(**Participents in the survery are randomly selected females from each country)) by(country, total)
